---
language: minimal

jobs:
  include:
    - name: focal (20.04)
      os: linux
      dist: focal
      install: >-
        cd /tmp
        && wget 'https://ftp.gnu.org/gnu/make/make-4.4.1.tar.gz'
        && tar xzf make-4.4.1.tar.gz
        && cd make-4.4.1
        && ./configure --prefix=/usr/local
        && sudo make install
      script: make test

    - name: jammy (22.04)
      os: linux
      dist: jammy
      install: >-
        cd /tmp
        && wget 'https://ftp.gnu.org/gnu/make/make-4.4.1.tar.gz'
        && tar xzf make-4.4.1.tar.gz
        && cd make-4.4.1
        && ./configure --prefix=/usr/local
        && sudo make install
      script: make test

    - name: osx xcode12
      os: osx
      osx_image: xcode12
      before_install: brew update
      install: brew install make git
      script: PATH="$HOMEBREW_PREFIX/opt/make/libexec/gnubin:$PATH" make test
