---
language: minimal
os:
  - linux
  - osx

jobs:
  include:
    - name: focal (20.04)
      os: linux
      dist: focal
    - name: jammy (22.04)
      os: linux
      dist: jammy
    - name: osx xcode12
      os: osx
      osx_image: xcode12

before_install: |
  if [ 'osx' = "${TRAVIS_OS_NAME}" ]; then
    brew update
  fi

install: |
  if [ 'osx' = "${TRAVIS_OS_NAME}" ]; then
    brew install make
  fi

script: |
  if [ 'osx' = "${TRAVIS_OS_NAME}" ]; then
    gmake test
  else
    make test
  fi
