---
language: minimal
os:
  - linux
  - osx

jobs:
  include:
    - name: focal (20.04)
      os: linux
      dist: focal
      script: make test

    - name: jammy (22.04)
      os: linux
      dist: jammy
      script: make test

    - name: osx xcode12
      os: osx
      osx_image: xcode12
      before_install: brew update
      install: brew install make git bash
      script: gmake test

  exclude:
    - name: xenial (16.04)
      os: linux
      dist: xenial

    - name: osx xcode9.4
      os: osx
      osx_image: xcode4.4
