---
language: minimal
services:
  - docker

jobs:
  include:

    ####################################################################################################
    - stage: test

    - name: focal (20.04)
      os: linux
      dist: focal
      install: >-
        pushd /tmp
        && wget 'https://ftp.gnu.org/gnu/make/make-4.4.1.tar.gz'
        && tar xzf make-4.4.1.tar.gz
        && cd make-4.4.1
        && ./configure --prefix=/usr/local
        && sudo make install
        && popd
      script: >-
        export TMPDIR=$(mktemp -d)
        && export PATH="/usr/local/bin:$PATH"
        && make test
        && make PREFIX=${TMPDIR}/ install

    - name: jammy (22.04)
      os: linux
      dist: jammy
      install: >-
        pushd /tmp
        && wget 'https://ftp.gnu.org/gnu/make/make-4.4.1.tar.gz'
        && tar xzf make-4.4.1.tar.gz
        && cd make-4.4.1
        && ./configure --prefix=/usr/local
        && sudo make install
        && popd
      script: >-
        export TMPDIR=$(mktemp -d)
        && export PATH="/usr/local/bin:$PATH"
        && make test
        && make PREFIX=${TMPDIR}/ install

    # Only run for the main branch.
    # Travis OSX jobs are 5x more expensive than Linux ones.
    - name: osx xcode12
      if: commit_message =~ /build\!osx/
      os: osx
      osx_image: xcode12
      before_install: brew update
      install: >-
        brew install make git bash
      script: >-
        export TMPDIR=$(mktemp -d)
        && export PATH="/usr/local/opt/make/libexec/gnubin:$PATH"
        && make test
        && make PREFIX=${TMPDIR}/install


    ####################################################################################################
    - stage: build

    - name: build
      os: linux
      dist: jammy
      install: >-
        pushd /tmp
        && wget 'https://ftp.gnu.org/gnu/make/make-4.4.1.tar.gz'
        && tar xzf make-4.4.1.tar.gz
        && cd make-4.4.1
        && ./configure --prefix=/usr/local
        && sudo make install
        && popd
      script: >-
        make package-rpm package-deb
