---
language: shell

os: linux
dist: xenial

services:
  - docker

####################################################################################################
jobs:

  exclude:
    - dist: xenial

  include:

    ################################################################################################

    - stage: test

    - &linux
      name: Focal (20.04)
      os: linux
      dist: focal
      install: >-
        pushd /tmp
        && wget 'https://ftp.gnu.org/gnu/make/make-4.4.1.tar.gz'
        && tar xzf make-4.4.1.tar.gz
        && cd make-4.4.1
        && ./configure --prefix=/usr/local
        && sudo make install
        && popd
      script: >-
        export TMPDIR=$(mktemp -d)
        && export PATH="/usr/local/bin:$PATH"
        && make test
        && make PREFIX=${TMPDIR}/ install

    - <<: *linux
      name: Jammy (22.04)
      os: linux
      dist: jammy

    # Only run for the main branch.
    # Travis OSX jobs are 5x more expensive than Linux ones.
    - name: OSX (xcode 12)
      if: commit_message =~ /build\!osx/
      os: osx
      osx_image: xcode12
      before_install: brew update
      install: >-
        brew install make git bash
      script: >-
        export TMPDIR=$(mktemp -d)
        && export PATH="/usr/local/opt/make/libexec/gnubin:$PATH"
        && make test
        && make PREFIX=${TMPDIR}/install

    ################################################################################################

    - stage: build

    - <<: *linux
      name: Build DEB and RPM packages
      os: linux
      dist: focal
      script: >-
        make package-rpm package-deb

    ################################################################################################

    - stage: deploy

    - name: Create github release
      os: linux
      dist: focal
      before_deploy: >-
        [[ -z "$BMAKELIB_VERSION" ]] && export BMAKELIB_VERSION="$(<src/VERSION)"
      deploy:
        provider: releases
        draft: true
        cleanup: false
        overwrite: true
        on:
          tags: true
        token:
          secure: 'ilFr/G75yFMYV5tNDEbt9xtGWoB1tWZdYh4oiGpx20TxK283NW3MJ/cZxQLTs1fBRe8DYRLiAzYdTfdLzjtKyCUfKkTaBCOIs4kKRphd3Od4iNI42AgA6hyT8edeCsyDd0uTui+ZDi7Z2rGCW29PDvWh67GZ31ksTl5bWj+gWtU0Hc+KnBBFGQ+N9U1aC1l7SYnKnGzPrtguoEDKBVoA5lURLc/dmoA51ACV921lJwSALsHwTqSVpW5cS+1xnTOXaFDsm6ebjG8mygzLBv6D54/GnYnpEBt+NhoXtHRP2Q+fWLqlxEDyj8xP8/eE5o/okl1LMz1d8fthYHh6duBT0O8GL6TMlMZAJClTYMPuFbLSyNkHynHjdztGZHZPsTX8zJoizPNVbZE+pr5eydaY6y6Uzp0wJGxb+dNrGfuc0EaPGHb904i32PqSb/AeAFrVHUXTvFlu8zIURe5AcegthCZUAULzAxLcpMX31/yicbNyKph4q7MktzWsYWJ8wuAsCjOLS9yaSkQM7jbTzsG+Xaz2KrQtL52//pLMCYzMPHOxrrtRiCVEhRmQ5K4Z8020yfYPEzOSedZHN1ySIvhLgoCEWRETA9/PGXTa+1JthHNjkciO5e3FPyYu+Lze1UGYO4S4JEwMpH50tJber1sm3PYuYUu5W6EQBL4ORns9b/s='
        file_glob: true
        file:
          - dist/bmakelib-${BMAKELIB_VERSION}.tar.gz
          - dist/bmakelib-${BMAKELIB_VERSION}-*.noarch.rpm
          - dist/bmakelib_${BMAKELIB_VERSION}-*_all.deb
