---
version: 2.1

####################################################################################################

executors:
  ubuntu2204:
    resource_class: medium
    machine:
      image: ubuntu-2204:current

####################################################################################################

jobs:

  test:
    executor: ubuntu2204
    steps:
      - run:
          name: Install the development tools
          command: >-
            pushd /tmp
            && wget 'https://ftp.gnu.org/gnu/make/make-4.4.1.tar.gz'
            && tar xzf make-4.4.1.tar.gz
            && cd make-4.4.1
            && ./configure --prefix=/usr/local
            && sudo make install
            && popd

      - checkout

      - run:
          name: Run the tests
          command: >-
            make test

    working_directory: ~/bmakelib

####################################################################################################

workflows:
  build_test_deploy:
    jobs:
      - test
