---
version: 2.1

####################################################################################################

executors:
  ubuntu2204:
    resource_class: medium
    machine:
      image: ubuntu-2204:current

  mac:
    resource_class: macos.m1.medium.gen1
    macos:
      xcode: 15.2.0

####################################################################################################

jobs:

  test_linux:
    executor: ubuntu2204
    steps:
      - run:
          name: Install the development tools
          command: >-
            pushd /tmp
            && wget 'https://ftp.gnu.org/gnu/make/make-4.4.1.tar.gz'
            && tar xzf make-4.4.1.tar.gz
            && cd make-4.4.1
            && ./configure --prefix=/usr/local
            && sudo make install
            && popd

      - run:
          name: Debug - Check versions
          command: >-
            bash --version
            && make --version
            && find --version
            && mktemp --version
            && xargs --version

      - checkout

      - run:
          name: Run the tests and Install bmakelib
          command: >-
            export PATH="/usr/local/bin:$PATH"
            && export TMPDIR=$(mktemp -d)
            && make --debug=jobs PREFIX=${TMPDIR}/ test install

    working_directory: ~/bmakelib

  test_mac:
    executor: mac
    steps:
      - run:
          name: Install the development tools
          command: >-
            brew install make git bash

      - checkout

      - run:
          name: Run the tests and Install bmakelib
          command: >-
            export PATH="/opt/homebrew/opt/make/libexec/gnubin:$PATH"
            && export TMPDIR=$(mktemp -d)
            && make PREFIX=${TMPDIR}/ test install

    working_directory: ~/bmakelib

####################################################################################################

workflows:
  build_test_deploy:
    jobs:
      - test_linux
#      - test_mac
